[[actions]]
name = "play"
platform = "windows"
path = "DoublePatches/DoublePatches.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "DoublePatches/DoublePatches"
args = ["--launched-through-itch"]
